kind: pipeline
type: docker
name: webUITest

platform:
  os: linux
  arch: amd64

steps:
  - name: server
    image: node:14
    detach: true
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: waveentry
      SERVER_PORT: 3001
      JWT_SECRET: very-secret
    commands:
      - git clone --single-branch -b master --depth 1 https://github.com/saw-jan/wave-entry-server.git /tmp/server
      - cd /tmp/server
      - npm ci
      - npm run db:seed
      - npm start

  - name: web-client
    image: node:14
    detach: true
    environment:
      REACT_APP_SERVER_URI: http://server:3001
    commands:
      - npm ci
      - BROWSER=none npm start

  - name: wait-for-servers
    image: owncloudci/wait-for:latest
    commands:
      - wait-for -it server:3001 -t 300
      - wait-for -it web-client:3000 -t 300

  - name: acceptance-tests
    image: node:14
    environment:
      SERVER_URL: http://server:3001
      WEB_URL: http://web-client:3000
    commands:
      - npm run setup:e2e
      - npm run test:e2e tests/acceptance/features/login.feature

services:
  - name: mongodb
    image: mongo:focal

trigger:
  branch: master
