kind: pipeline
type: docker
name: DroneCITest

steps:
  - name: waveentry-server
    image: owncloudci/nodejs:14
    detach: true
    environment:
      DB_HOST: mongodatabase
      DB_PORT: 27017
      DB_NAME: waveentrydatabase
      SERVER_PORT: 3001
      JWT_SECRET: abcd1234
    commands:
      - git clone https://github.com/SagarGi/wave-entry-server.git /waveentryserver
      - cd /waveentryserver
      - npm ci
      - npm start

  - name: waveentryUI
    image: owncloudci/nodejs:14
    detach: true
    environment:
      REACT_APP_SERVER_URI: http://waveentry-server:3001
    commands:
      - npm ci
      - BROWSER=none npm start
  - name: wait
    image: owncloudci/wait-for:latest
    commands:
      - wait-for -it waveentry-server:3001 -t 300
      - wait-for -it waveentryUI:3000 -t 300

  - name: acceptanceTest
    image: owncloudci/nodejs:14
    environment:
      SERVER_URL: http://waveentry-server:3001
      WEB_URL: http://waveentryUI:3000
    commands:
      - npm run test:e2e ./tests/acceptance/features/

services:
  - name: mongodatabase
    image: mongo

trigger:
  branch:
    - master
